### ISSUE TITLE
feature request: allow for multiple go source files

### ISSUE THREAD

**Issue by umbellate** [fumeapp/fume-cli#47]
I have lambdas that are just complicated enough to want warrant multiple go source files in order to keep me sane. Unfortunately, deploytasks just wants one source file. This is all fine and good and I can deal with it, but the problem occurs when I need to debug something: since i cannot have multiple files, i end up importing my code from another module and using in main.go... in debugging, this may result in my having to update the module and then the lambda's go.mod... so that's 2 commits (one for module one for lambda) and 3 pushes (1 for module, 1 for lambda main, 1 for lambda production). It would help to be able to gather all the go sources in the directory and include them in the build line:

```
./src/lib/deploytasks.ts:273:    await execa('go', ['build', '-o', 'main', 'main.go'], { env: { GOOS: 'linux', GOARCH: 'amd64' } })
```

I can do this, likely, but I do not know js/typescript so I cannot whip out a change real quick. I'm guessing one can just use glob or another something from `fs`. Since it's probably something I should just learn and know for future, I will look to add this and submit a PR, but wanted to make issue first in case I should not.

**Comment by acidjazz** [comment]
So.. I'm still new to Go.. but doesn't the import of the other source files take care of this? how does specifying multiple files in the build help debug? Do you get better error reporting?

**Comment by umbellate** [comment]
The point is that I don't want to have to import from another module. If I do that, any time I want to update the bits that are in the other module, I have to do the multiple commits and pushes to get it deployed. Using multiple files in `go build`, e.g. `go build main.go foo.go` is akin to compiling a C program `cc -o yourexecutablename main.c foo.c` This has nothing to do with debug or better reporting, but rather being able to have code in the `main` package of the lambda in multiple files.  I just do not want to be constrained to a single file for my code.

An example of wanting to do something like this would be to separate out some longer routines into another file for readability sake. Or say I am implementing a type with some type receiver routines, it is nice to be able to put all that related code in a single place, perhaps outside of file where code using it.

**Comment by umbellate** [comment]
This is closed, but an untested possible solution to what I'd like would be:

```
diff --git a/src/lib/deploytasks.ts b/src/lib/deploytasks.ts
index 74aec6d..5e5437b 100644
--- a/src/lib/deploytasks.ts
+++ b/src/lib/deploytasks.ts
@@ -267,10 +267,23 @@ exports.handler = async (event, context) => {
     await execa(this.packager, args)
   }
 
+  async goFindSourceFiles(task: ListrTaskWrapper<any, any>) {
+    var sources = [];
+    fs.readdirSync('.').forEach(file => {
+      if (file.endsWith('.go')) {
+        sources.push(file);
+      }
+    });
+    return sources
+  }
+
   async goCompile(task: ListrTaskWrapper<any, any>) {
     task.title = 'Compiling go binary'
     await this.deployment.update('GO_COMPILE')
-    await execa('go', ['build', '-o', 'main', 'main.go'], { env: { GOOS: 'linux', GOARCH: 'amd64' } })
+    var sources = await goFindSourceFiles(task) 
+    var build = ['build', '-o', 'main']
+    var fullBuild = build.concat(sources)
+    await execa('go', fullBuild, { env: { GOOS: 'linux', GOARCH: 'amd64' } })
   }
 
   async goArchive(task: ListrTaskWrapper<any, any>) {
```
